import json
from typing import Dict, List

CATEGORY_STRING = """
{
    "metadata": [
        "cancelable",
        "roomcategory",
        "locationtype",
        "locationname"
    ],
    "price_rating": [
        "pricepernight",
        "rating",
        "ratingscount",
        "popular_location_rank",
        "starcategory"
    ],
    "distances": [
        "distancetocity",
        "distancetounderground",
        "distancetobeach",
        "distancetobathing",
        "distancetoairport",
        "distancetotrainstation"
    ],
    "safety_health": [
        "24-Stunden-Rezeption",
        "24-Stunden-Sicherheitspersonal",
        "Bestätigte Corona-Schutzmaßnahmen",
        "Desinfektion von Geschirr",
        "Feuerlöscher",
        "Keine Corona-Schutzmaßnahmen",
        "Kontaktlose Bezahlung",
        "Kontaktloser Check-In/out",
        "Kostenloses Handdesinfektionsmittel",
        "Maskenpflicht",
        "Mitarbeiter tragen Schutzkleidung",
        "Reinigung mit Desinfektionsmittel",
        "Reinigungsmittel gegen Coronaviren",
        "Sicherheitsalarm",
        "Videoüberwachung der Außenbereiche der Unterkunft",
        "Videoüberwachung in Gemeinschaftsräumen"
    ],
    "food_beverage": [
        "Abendessen",
        "Bar",
        "Barrierefrei",
        "Barrierefreie Dusche",
        "Café",
        "Cash (Bargeld)",
        "Einzeln verpackte Essenspakete verfügbar",
        "Frühstück",
        "Frühstücksbuffet",
        "Gemeinschaftsküche",
        "Getränke/Snackautomat",
        "Grillmöglichkeiten",
        "Handschuhe für Gäste verfügbar",
        "Kinderfreundliches Buffet",
        "Kontinentales Frühstück",
        "Küche",
        "Masken für Gäste verfügbar",
        "Minibar",
        "Obere Stockwerke mit Fahrstuhl erreichbar",
        "Picknickbereich",
        "Poolbar",
        "Privates Abendessen",
        "Restaurant",
        "Schutzkleidung für Gäste verfügbar",
        "Snackbar",
        "Strandbar",
        "Strom aus erneuerbaren Energien",
        "Visuelle Hilfe: fühlbare Zeichen",
        "Vollwertiges Frühstück",
        "mealtype"
    ],
    "sport_recreation": [
        "Abenteuer",
        "Aerobic",
        "Billard",
        "Darts",
        "Fahrradstellplatz",
        "Fahrradtouren",
        "Fahrradvermietung",
        "Fitness",
        "Fitnesseinrichtung",
        "Gesicherte Fahrradstellplätze",
        "Golf/Sport",
        "Golfplatz (max. 3 km entfernt)",
        "Golfunterricht",
        "Kanusport",
        "Minigolf",
        "Radfahren",
        "Reiten",
        "Tennisausrüstung",
        "Tennisplatz",
        "Tischtennis",
        "Wandern",
        "Wassersportmöglichkeiten vor Ort",
        "Wasserpark",
        "Wasserrutsche"
    ],
    "room_amenities": [
        "WLAN",
        "LAN",
        "Adapter/Ladegeräte",
        "Aufdeckservice",
        "Babybadewanne",
        "Bademantel",
        "Badewanne oder Dusche",
        "Balkon",
        "Bettwäsche",
        "Dampfbad",
        "Deckenventilator",
        "Dusch-Badewannen Kombination",
        "Eigenes Badezimmer",
        "Essen kann auf das Zimmer geliefert werden",
        "Familienzimmer vorhanden",
        "Flachbild-TV",
        "Fußbad",
        "Föhn",
        "Gast kann Zimmerreinigung abmelden",
        "Gefrierschrank",
        "Gemeinschaftsbad",
        "Gemeinschaftslounge/TV-Bereich",
        "Halboffenes Badezimmer",
        "Heizung",
        "Heizung im Zimmer steuerbar",
        "Hypoallergene Bettware erhältlich",
        "Individuell dekoriert je Zimmer",
        "Individuelle Möbel je Zimmer",
        "Kabel TV",
        "Kinder-/Babybetten auf Anfrage",
        "Kinderbetreuung im Zimmer",
        "Klimaanlage im Zimmer",
        "Klimaanlage im Zimmer steuerbar",
        "Klimaanlage in allen Zimmern",
        "Kühlschrank",
        "Kühlschrank im Gemeinschaftsbereich",
        "Mikrowelle",
        "Mikrowelle im Gemeinschaftsbereich",
        "Mini-Kühlschrank",
        "Nichtraucherzimmer",
        "Niedriges Waschbecken",
        "Niedriges Waschbecken im Bad",
        "Notrufleine im Bad",
        "Premium Bettwaren",
        "Raucher und Nichtraucherzimmer",
        "Raucherzimmer",
        "Safe an der Rezeption",
        "Safe im Zimmer",
        "Safe in Laptopgröße",
        "Satelliten-TV",
        "Schlafsofa",
        "Schlafzimmer",
        "Schrank",
        "Schreibtisch",
        "Schwimmbad",
        "Smart TV",
        "Streaming-Dienste (z.B. Netflix)",
        "Streaming-Service",
        "TV",
        "Tagesbett",
        "Ventilator",
        "Waschsalon/Wäscheservice",
        "Wassereinsparende Badezimmer-Einrichtungen",
        "Wasserkocher",
        "Whirlpool-Badewanne",
        "Wohnzimmer",
        "Wäsche wird nach regionalem Standard gewaschen",
        "Zimmer mit Verbindungstür",
        "Zimmerreinigung",
        "Zimmerreinigung (eingeschränkt)",
        "Zimmerservice",
        "Zimmerservice (eingeschränkt)",
        "Zustellbett auf Anfrage",
        "Zustellbetten",
        "iPod-Dockingstation",
        "Übergroße Badewanne"
    ],
    "payment_methods": [
        "American Express",
        "Diners Club",
        "Discover",
        "Eurocard/Mastercard",
        "JCB",
        "Maestro",
        "Visa"
    ],
    "entertainment": [
        "Animation (Erwachsene)",
        "Karaoke",
        "Live-Musik/Performance",
        "Motto-Dinnerabende",
        "Nachtclub/DJ",
        "Pub Crawl"
    ],
    "style_theme": [
        "Aparthotel",
        "Boutique-/Designhotel",
        "Boutiquen/Läden",
        "Gasthaus",
        "Luxushotel",
        "Panoramahotel",
        "Pension",
        "Resort",
        "Romantik/Flitterwochen",
        "Strandhotel"
    ],
    "languages": [
        "Arabisch",
        "Bosnisch",
        "Deutsch",
        "Englisch",
        "Französisch",
        "Italienisch",
        "Japanisch",
        "Kroatisch",
        "Niederländisch",
        "Polnisch",
        "Portugiesisch",
        "Rumänisch",
        "Russisch",
        "Serbisch",
        "Slowakisch",
        "Thailändisch",
        "Tschechisch",
        "Ungarisch",
        "Spanisch"
    ],
    "business_events": [
        "Arbeitsbereich für Arbeit mit Laptop geeignet",
        "Businesscenter",
        "Businesshotel",
        "Computerarbeitsplatz",
        "Fax/Kopierer",
        "Konferenz- und Veranstaltungsräume"
    ],
    "pets": [
        "Assistenztiere sind von Gebühren/ Restriktionen ausgeschlossen",
        "Budgetorientiert",
        "Haustiere erlaubt",
        "Haustierfreundliches Hotel",
        "Hundeauslaufplatz",
        "Nur Assistenztiere sind erlaubt",
        "Nur Hunde sind erlaubt",
        "Nur Hunde und Katzen sind erlaubt",
        "Portier/Hotelpage",
        "Tierkörbchen"
    ],
    "other_amenity": [
        "Aufzug",
        "Ausflugsinformationen",
        "Ausgewiesene Raucherbereiche",
        "Backofen",
        "Bankettsaal",
        "Besichtigungstouren",
        "Bibliothek",
        "Bidet",
        "Bücher",
        "Bügeleinrichtungen",
        "Bügelservice",
        "Concierge Service",
        "Dachterrasse",
        "Daunenkissen",
        "Dusche",
        "Duschhocker",
        "Espressomaschine",
        "Essbereich",
        "Esstisch",
        "Express-Check-in/-out",
        "Filme",
        "Friseur-/Schönheitssalon",
        "Futternapf",
        "Ganzkörperpackung",
        "Garten",
        "Geldautomat vor Ort",
        "Geldwechsel",
        "Gepäckaufbewahrung",
        "Gesamte Wohneinheit im Erdgeschoß",
        "Geschenkeladen/ Zeitungsstand",
        "Gesichtsbehandlungen",
        "Gäste werden auf Gesundheit kontrolliert",
        "Haarentfernung mit Wachs",
        "Handtücher",
        "Hausschuhe",
        "Heiße Quelle",
        "Hochzeitsservice",
        "Hotel",
        "Kaffee/Tee in Gemeinschaftsräumen",
        "Kapelle/Schrein",
        "Keine oder eingeschränkte Verwendung von Plastik-Artikeln (z.B. Strohhalme",
        "Besteck oder Einweg-Artikel)",
        "Kissenauswahl",
        "Kitchenette",
        "Kochplatten/ Herd",
        "Kochutensilien",
        "Kunstgalerie im Hotel",
        "Körperpeeling",
        "Kühl-Gefrierkombination",
        "LGBT-Freundlich",
        "Lokale Karten",
        "Lunchpakete",
        "Maniküre",
        "Mehrsprachiges Personal",
        "Minimarkt vor Ort",
        "Mitarbeiter folgen Regeln des regionalen Standards",
        "Nichtraucherunterkunft",
        "Nichtschwimmerbereich",
        "Nur für Erwachsene",
        "Pediküre",
        "Pflegeprodukte",
        "Pillow-Top Matratze",
        "Privater Check-in/-out",
        "Privater Strand",
        "Privates Tauchbecken",
        "Privatstrand in der Nähe",
        "Rauchmelder",
        "Regendusche",
        "Reiseführer oder Empfehlungen",
        "Rezeption",
        "Räumliche Trennung von Gästen und Mitarbeitern in Hauptkontaktzonen",
        "Schallisolierung",
        "Schließfächer",
        "Seife",
        "Shampoo",
        "Shopping",
        "Sitzecke",
        "Social Distancing Maßnahmen",
        "Solarium",
        "Sonnenschirme",
        "Sonnenstühle/-liegen",
        "Speisen für spezielle Ernährungsbedürfnisse",
        "Spülmaschine",
        "Strand",
        "Strand Cabana",
        "Städtereise",
        "Tauchbecken",
        "Tee-/Kaffeezubereiter",
        "Telefon",
        "Terrasse",
        "Ticketservice",
        "Toilettenpapier",
        "Touren/Kurse über die örtliche Kultur",
        "Unterkunft wird von professionellem Reinigungsservice gereinigt",
        "Vegan",
        "Vegetarisch",
        "Veranda/Terrasse",
        "Verdunkelungsvorhänge",
        "Versiegelung des Raums nach Reinigung",
        "Wickeltisch",
        "Yoga",
        "Zahnbürste",
        "Zeitlicher Abstand zwischen Aufenthalten von Gästen eingeführt",
        "Zeitung",
        "Zeitungen in der Lobby",
        "ländlich"
    ],
    "transport_parking": [
        "Autovermietung",
        "Flughafenshuttle",
        "Gesicherte Parkplätze",
        "Kostenlos parken vor Ort",
        "Ladestation für Elektro-Autos",
        "Langzeitparken",
        "Parken vor Ort",
        "Parkhaus/Tiefgarage",
        "Parkplatz außerhalb des Hotelgeländes",
        "Parkservice",
        "Shuttle in die Umgebung",
        "Shuttle zum Bahnhof",
        "Shuttle zur Fähre",
        "Shuttleservice"
    ],
    "wellness_spa": [
        "Hydromassage Dusche",
        "Sauna",
        "Spa & Wellnesscenter",
        "Spa-Anwendungen",
        "Spa/Entspannung",
        "Wellness",
        "Wellnessangebote",
        "Wellnessbehandlungsraum/-räume",
        "Wellnesshotel",
        "Wellnesslounge/Ruhebereich",
        "Pool",
        "Massage"
    ],
    "family_kids": [
        "Baby-/ Kinderbetreuung",
        "Betreute Kinderaktivitäten",
        "Brettspiele/Puzzle",
        "Buggys",
        "Familie",
        "Geschirr für Kinder",
        "Kinderbecken",
        "Kinderbücher",
        "Kinderclub",
        "Kinderhochstuhl",
        "Kindermahlzeiten",
        "Kinderspielplatz",
        "Outdoorspielgeräte für Kinder",
        "Spielbereich",
        "Spiele für Kinder",
        "Spielhalle",
        "Spielzeug",
        "Wasserspielzeug für Kinder"
    ],
    "accessibility": [
        "Behindertenfreundlich",
        "Behindertengerechte Parkplätze",
        "Gesamte Wohneinheit ist rollstuhlgerecht",
        "Höheres WC",
        "Hörhilfen",
        "Nicht rollstuhlgerecht",
        "Rollstuhlgerecht",
        "Visuelle Hilfe: Braille",
        "WC mit Haltegriffen",
        "Zugang über außengelegene Gänge",
        "direkter Strandzugang (privater Strand)",
        "Rollstühle verfügbar"
    ],
    "sustainability": [
        "Investitionen in lokale Nachhaltigkeitsprojekte",
        "Lebensmittel aus biologischem Anbau",
        "Lebensmittel aus der Region",
        "Maßnahmen zur Reduzierung des Energieverbrauchs",
        "Nachhaltige Unterkunft",
        "Programm zur Reduzierung von Lebensmittelabfällen",
        "Recycling",
        "Teile des CO²-Ausstoßes werden durch Zertifikate ausgeglichen"
    ]
}
"""

def load_grouped_columns_from_json_string(json_string: str) -> dict[str, list[str]]:
    data = json.loads(json_string)

    # Sicherheitsprüfungen
    if not isinstance(data, dict):
        raise ValueError("JSON content must be a dictionary.")

    for key, value in data.items():
        if not isinstance(key, str) or not isinstance(value, list):
            raise ValueError(
                "Each key must be a string and each value must be a list of strings."
            )
        if not all(isinstance(item, str) for item in value):
            raise ValueError("Each item in the value lists must be a string.")

    return data 